//
//  FeedPresenter.swift
//  Catogram
//
//  Created Олег Крылов on 07/08/2019.
//  Copyright © 2019 OlegKrylov. All rights reserved.
//
//  Template generated by Edward
//

import Foundation

// MARK: View -
protocol FeedViewProtocol: AnyObject {
    func setupViewWithCat(cat: ImageResponse)
    
}

// MARK: Presenter -
protocol FeedPresenterProtocol: AnyObject {
    var view: FeedViewProtocol? { get set }
    
    func viewDidLoad()
    func getRandomImage()
    func voteUpForCurrentImage()
    func voteDownForCurrentImage()
    func favCurrentImage()
}
class FeedPresenter: FeedPresenterProtocol {
    
    weak var view: FeedViewProtocol?
    private var randomImage: ImageResponse? = nil
    private let imageNetworkProtocol = NetworkService(urlFactory: URLFactory())
    
  
    
    func viewDidLoad() {
        getRandomImage()
    }
    
    func getRandomImage() {
        self.imageNetworkProtocol.getRandomImage { result in
            switch result {
            case .success(let response):
               self.randomImage = response[0]
               self.view?.setupViewWithCat(cat: self.randomImage!)
            case .failure(let error):
                print(error)
            }
        }
    }
    
    func voteUpForCurrentImage() {
        self.imageNetworkProtocol.voteForCurrentImage(id: (self.randomImage?.id)!, vote: 1, completion: { result in
            switch result {
            case .success(let response):
                print(response.message)
            case .failure(let error):
                print(error)
            }
        })
        self.getRandomImage()
    }
    
    func voteDownForCurrentImage() {
        self.imageNetworkProtocol.voteForCurrentImage(id: (self.randomImage?.id)!, vote: 0, completion: { result in
            switch result {
            case .success(let response):
                print(response.message)
            case .failure(let error):
                print(error)
            }
        })
        self.getRandomImage()
    }
    
    func favCurrentImage() {
        self.imageNetworkProtocol.favCurrentImage(id: (self.randomImage?.id)!, completion: { result in
            switch result {
            case .success(let response):
                print(response.message)
            case .failure(let error):
                print(error)
            }
        })
    }
    
    
    
}

