//
//  FavouritesViewController.swift
//  Catogram
//
//  Created Олег Крылов on 12/08/2019.
//  Copyright © 2019 OlegKrylov. All rights reserved.
//
//  Template generated by Edward
//

import UIKit

final class FavouritesViewController: UIViewController, FavouritesViewProtocol {
    
    var presenter: FavouritesPresenterProtocol
    private let favouritesCollectionView: UICollectionView
    private var viewModels = [FavouritesViewModel]()
    private var imageTasks = [Int: ImageTask]()
    
    init(presenter: FavouritesPresenterProtocol) {
        self.presenter = presenter
        let collectionViewLayout = UICollectionViewFlowLayout()
        self.favouritesCollectionView = UICollectionView(frame: .zero, collectionViewLayout: collectionViewLayout)
        super.init(nibName: nil, bundle: nil)
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        presenter.view = self
        presenter.viewDidLoad()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        presenter.getFavouritesImages()
    }
    
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        setupCollectionView()
        self.favouritesCollectionView.frame = self.view.bounds
        self.favouritesCollectionView.backgroundColor = .white
    }
}

extension FavouritesViewController {
    func setupfavouritesCollectionView() {
        self.setupImageTasks(totalImages: self.viewModels.count)
        self.favouritesCollectionView.reloadData()
    }
    
    private func setupImageTasks(totalImages: Int) {
        let session = URLSession(configuration: URLSessionConfiguration.default)
        
        for i in 0..<totalImages {
            let url = URL(string: self.viewModels[i].imageUrl)!
            let imageTask = ImageTask(position: i, url: url, session: session, delegate: self)
            imageTasks[i] = imageTask
        }
    }
    
    func setupCollectionView() {
        self.favouritesCollectionView.dataSource = self
        self.favouritesCollectionView.delegate = self
        self.favouritesCollectionView.register(FavouritesCollectionViewCell.self, forCellWithReuseIdentifier: "FavouriteCell")
        self.favouritesCollectionView.contentInset = UIEdgeInsets(top: 5, left: 5, bottom: 5, right: 5)
        self.view.addSubview(favouritesCollectionView)
    }
    
    func set(viewModels: [FavouritesViewModel]) {
        self.viewModels = viewModels
    }
}

extension FavouritesViewController: UICollectionViewDataSource {
    
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return viewModels.count
    }
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "FavouriteCell", for: indexPath) as! FavouritesCollectionViewCell
        let image = imageTasks[indexPath.row]?.image
        cell.set(image: image)
        return cell
    }
    
    
}

extension FavouritesViewController: UICollectionViewDelegate {
    func collectionView(_ collectionView: UICollectionView, willDisplay cell: UICollectionViewCell, forItemAt indexPath: IndexPath) {
        imageTasks[indexPath.row]?.resume()
    }
    
    func collectionView(_ collectionView: UICollectionView, didEndDisplaying cell: UICollectionViewCell, forItemAt indexPath: IndexPath) {
        imageTasks[indexPath.row]?.pause()
    }
}

extension FavouritesViewController: UICollectionViewDelegateFlowLayout {
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
        let ratio: CGFloat = 1.2
        let width = collectionView.frame.width/3 - collectionView.contentInset.left - collectionView.contentInset.right
        let height = width * ratio
        return CGSize(width: width, height: height)
    }
}

extension FavouritesViewController: ImageTaskDownloadedDelegate {
    func imageDownloaded(position: Int) {
        self.favouritesCollectionView.reloadItems(at: [IndexPath(row: position, section: 0)])
    }
}
