//
//  LoginPresenter.swift
//  Catogram
//
//  Created Олег Крылов on 07/08/2019.
//  Copyright © 2019 OlegKrylov. All rights reserved.
//
//  Template generated by Edward
//

import Foundation

// MARK: View -
protocol LoginViewProtocol: class {
    func setupLoginView(login: String?)
}

// MARK: Presenter -
protocol LoginPresenterProtocol: class {
	var view: LoginViewProtocol? { get set }
    func viewDidLoad()
}

class LoginPresenter: LoginPresenterProtocol {
    
    weak var view: LoginViewProtocol?

    func viewDidLoad() {
        var login = UserDefaults.standard.stringArray(forKey: "userAuth")
        guard let logins = login?[0] else {
            self.view?.setupLoginView(login: nil)
            return
        }
        self.view?.setupLoginView(login: logins)
    }
}
