//
//  SearchPresenter.swift
//  Catogram
//
//  Created Олег Крылов on 18/08/2019.
//  Copyright © 2019 OlegKrylov. All rights reserved.
//
//  Template generated by Edward
//

import Foundation

// MARK: View -
protocol SearchViewProtocol: class {

}

// MARK: Presenter -
protocol SearchPresenterProtocol: class {
	var view: SearchViewProtocol? { get set }
    func viewDidLoad()
}

final class SearchPresenter: SearchPresenterProtocol {

    weak var view: SearchViewProtocol?

    func viewDidLoad() {

    }
}
